name: online-banking-app/account-service

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
        # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f account-service/requirements.txt ]; then pip install -r account-service/requirements.txt; fi
        
        # Linting step
      - name: Lint with flake8
        run: |
          flake8 account-service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 account-service --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

        # Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t sussap/account-service:latest account-service
        
        # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # push to DockerHub
      - name: Push to DockerHub
        run: |
          docker push sussap/account-service:latest
